<?php

use Illuminate\Database\Seeder;
use App\Plate;
use Illuminate\Support\Str;

class PlatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $plates =[
            // Mc Downalds Plates
            [
                "restaurant_id" => "14",
                "name" => "Crispy McBacon",
                "ingredients" => "Gluten (Wheat), Eggs, Milk, Celery, Mustard, Sesame Seeds",
                "description" => "Two 100% beef patties are combined with bacon, a slice of melted cheese and bacon sauce in a fresh bun, toasted for the right amount of crisp!",
                "visible" => true,
                "price" => 4,
                "img" => "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/element/2020-08/crispy-20anni--prod-02.png.webp?itok=-L3Ku-tF",
            ],
            [
                "restaurant_id" => "14",
                "name" => "My Selection BBQ",
                "ingredients" => "Gluten (Wheat), Eggs, Milk, Celery, Mustard, Sesame Seeds",
                "description" => "This legendary American burger is a true all-rounder! A 100% beef patty, Emmental cheese, onions, juicy tomatoes and a unique smoky flavoured sauce all nested in a freshly toasted bun. Make it even better - add crispy bacon.",
                "visible" => true,
                "price" => 5,
                "img" => "https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/myselection-bbq_isolated_0.png.webp?itok=Nib8-cBR",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Big Mac",
                "ingredients" => "Gluten (Wheat), Eggs, Milk, Celery, Mustard, Sesame Seeds, Sulphur Dioxide",
                "description" => "Two 100% beef patties, melted cheese, onions, pickles, lettuce and the signature Big Mac sauce make this an icon.",
                "visible" => true,
                "price" => 6,
                "img" => "https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/bigmac_isolated_0.png.webp?itok=bRODxB7w",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Cheeseburger",
                "ingredients" => "Gluten (Wheat), Eggs, Milk, Mustard, Sesame Seeds, Sulphur Dioxide",
                "description" => "A classic combination of a 100% pure beef patty, pickles, onion, mustard and ketchup and of course a slice of melted cheese in a freshly toasted bun make our cheeseburger a classic delight.",
                "visible" => true,
                "price" => 6,
                "img" => "https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/cheeseburger_isolated.png.webp?itok=m6DdWfU1",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Chicken Mayo",
                "ingredients" => "Gluten (Wheat), Gluten (Rye),Gluten (Barley), Gluten (Spelt), Eggs, Soybeans, Milk, Celery, Mustard, Sesame Seeds, Sulphur Dioxide",
                "description" => "A crispy 100% chicken patty nestled inside a freshly toasted bun with lettuce and a mayo sauce.",
                "visible" => true,
                "price" => 3.8,
                "img" => "https://www.mcdonalds.com.mt/wp-content/uploads/2018/05/chicken-mayo-classic.jpg",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Fries",
                "ingredients" => "Gluten (Wheat), Gluten (Rye), Gluten (Barley), Gluten (Oats), Gluten (Spelt), Gluten (Kamut), Crustaceans, Eggs, Fish, Milk, Peanuts, Tree Nuts (Pistachio nuts), Tree Nuts (Walnuts), Tree Nuts (Almonds), Tree Nuts (Hazelnuts), Tree Nuts (Brazil nuts) , Tree Nuts (Cashews), Tree Nuts (Macadamia), Tree Nuts (Queensland nuts), Tree Nuts (Pecan nuts), Celery, Mustard, Sesame Seeds, Soybeans, Sulphur Dioxide, Lupins or Molluscs",
                "description" => "A portion of delicious fries, cooked to golden perfection and seasoned with just the right amount of salt.",
                "visible" => true,
                "price" => 3,
                "img" => "https://www.mcdonalds.it/sites/default/files/product_category/thumb/patatine_thumb_search.jpg",
            ],
            [
                "restaurant_id" => "14",
                "name" => "McFlurry Bounty",
                "ingredients" => "Ice cream is a colloidal emulsion made with water, ice, milk fat, milk protein, sugar and air",
                "description" => "Ice cream is sweet, and is usually flavored with fruit, spices, or candy- the flavor often influences the color (that is, chocolate ice cream is brown, strawberry and cherry flavors are pink, pistachio is green)",
                "visible" => true,
                "price" => 3.4,
                "img" => "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/mcflurry-bounty--hero-mob.jpg.webp?itok=rMJ0uLKT",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Happy Meal",
                "ingredients" => "main item (a hamburger, cheeseburger or small serving of Chicken McNuggets), a side item (French fries, apple slices, a Go-Gurt tube or a salad in some areas) and a drink (milk, juice or a soft drink).",
                "description" => "Doesn’t matters if you want to be Wonder Woman or Batman… Or maybe secretly you love the Joker, come to your nearest McDonald’s and find them inside your Happy Meal!",
                "visible" => true,
                "price" => 3.4,
                "img" => "https://image.shutterstock.com/image-photo/kuala-lumpur-malaysia-february-17th-260nw-253256875.jpg",
            ],
            [
                "restaurant_id" => "14",
                "name" => "McToast with",
                "ingredients" => "bread cheese ham",
                "description" => "A freshly toasted bun served with a slice of melted cheese and two slices of juicy ham",
                "visible" => true,
                "price" => 2.5,
                "img" => "https://content.api.news/v3/images/bin/3b2afc8182d811d34e13a1bee51edcd3?width=650",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Fanta",
                "ingredients" => "orange, food coloring, water, phosphoric acid",
                "description" => "A tangy orange soda to complement all of our meals!",
                "visible" => true,
                "price" => 2,
                "img" => "https://www.ilpiaceredellacqua.com/wp-content/uploads/2018/07/fanta-lattina-33.jpg",
            ],
            [   
                "restaurant_id" => "14",
                "name" => "Coca-Cola Zero",
                "ingredients" => "phosphoric acid",
                "description" => "Coca-Cola Zero",
                "visible" => true,
                "price" => 2,
                "img" => "https://www.myamericanmarket.com/873/coca-cola-classic.jpg",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Scrambled Eggs",
                "ingredients" => "eggs, bread",
                "description" => "Looking to start your day with a smile? Try our scrambled eggs, also available with a side of mouth-watering crispy bacon. This breakfast option is also served as a combo with a choice of two drinks or a drink and a hash brown.",
                "visible" => true,
                "price" => 4.7,
                "img" => "https://d1nqx6es26drid.cloudfront.net/app/uploads/2015/04/04031748/product-big-breakfast.png",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Fruit Bag (Apple)",
                "ingredients" => "Apples",
                "description" => "Enjoy the healthy alternative with the Happy Meal! Our apples are fresh, sweet and incredibly crunchy keeping both you and your child happy thanks to their delicate flavour and high vitamin boosts!",
                "visible" => true,
                "price" => 2.2,
                "img" => "https://i.pinimg.com/originals/cf/2e/4b/cf2e4bc0c4e89ba937dcb8c5b5b0b4a7.png",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Vanilla Milkshake",
                "ingredients" => "Vanilla, milk",
                "description" => "A deliciously rich and creamy vanilla dairy milkshake that will leave you longing for more! Milkshake comes in regular size (25cl) and large size (40cl).",
                "visible" => true,
                "price" => 1.8,
                "img" => "https://www.mcdonalds.com/is/image/content/dam/usa/nfl/nutrition/items/hero/desktop/t-mcdonalds-Vanilla-McCafe-Shake-Medium.jpg",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Vanilla Cone",
                "ingredients" => "sugar, cream, vanilla",
                "description" => "Our signature creamy vanilla ice cream swirled to perfection into a crispy cone.",
                "visible" => true,
                "price" => 1.8,
                "img" => "http://www.cheaponana.com/wp-content/uploads/2016/03/cone.gif",
            ],
            [
                "restaurant_id" => "14",
                "name" => "Hash Brown",
                "ingredients" => "meat, olive oil",
                "description" => "Our potato hash browns are crispy and toasty on the outside while soft and fluffy inside. These crispy delights are a perfect addition to start off your day with a smile.",
                "visible" => true,
                "price" => 1.8,
                "img" => "https://149449860.v2.pressablecdn.com/wp-content/uploads/2019/02/RC-NEWS-Hashbrown-or-cellphone-0319.png",
            ],
            // Mc Burger King Plates
            [
                "restaurant_id" => "13",
                "name" => "DOUBLE CHICKEN BBQ",
                "ingredients" => "2 slices of cheddar, 4 slices of bacon, crunchy onion, Cheddar sauce and a yummy Bull's Eye BBQ sauce. Crazy Cheese BBQ is here, only for true cheese lovers.",
                "description" => "A classic combination of a 100% pure beef patty, pickles, onion, mustard and ketchup and of course a slice of melted cheese in a freshly toasted bun make our cheeseburger a classic delight.",
                "visible" => true,
                "price" => 4.6,
                "img" => "https://i.pinimg.com/originals/7f/aa/2a/7faa2a995bb9582c80adf84d6ac399d9.png",
            ],
            [
                "restaurant_id" => "13",
                "name" => "CRAZY CHEESE BBQ",
                "ingredients" => "bread, grilled meat, cheddar, bacon, BBQ sauce",
                "description" => "Two soft slices of corn bread contain 3 layers of grilled meat accompanied by American cheddar, 8 slices of bacon and the unmistakable smoky taste of the BBQ sauce. Great hunger? Epic sandwich.",
                "visible" => true,
                "price" => 4.9,
                "img" => "https://d1ralsognjng37.cloudfront.net/39e57b90-6583-4054-9c20-eb3c229d2fe6.jpeg",
            ],
            [
                "restaurant_id" => "13",
                "name" => "BIG KING XXL",
                "ingredients" => "bread, cheese, onion, grilled meat, cheddar, bacon, BBQ sauce",
                "description" => "Extra-Extra-Large! It is not just a maxi size, but a real challenge! With its double serving of juicy grilled meat, unique taste of the special sauce and not one, not two, but four slices of tasty Cheddar cheese the BIG KING® XXL wants to be tamed. Simply irresistible.",
                "visible" => true,
                "price" => 5.3,
                "img" => "https://www.burgerking.it/site/assets/files/8949396/bronx_steakhouse.png",
            ],
            [
                "restaurant_id" => "13",
                "name" => "TRIPLE WHOPPER",
                "ingredients" => " lettuce, tomato, bread, cheese, onion, grilled meat, bacon, BBQ sauce",
                "description" => "We know it's hard to get tired of our WHOPPER®, but for those who want more, we created the WHOPPER® Triple. Tomato, onion, cucumber and lettuce with our most famous burger, multiplied by three. A real treat with every bite!",
                "visible" => true,
                "price" => 4.7,
                "img" => "https://burgerking.com.mt/wp-content/uploads/2020/03/5.TRIPLE-WHOPPER.png",
            ],
            [
                "restaurant_id" => "13",
                "name" => "DOUBLE CHEESE BACON",
                "ingredients" => "cucumber, bread, cheese, onion, grilled meat, bacon, mustard",
                "description" => "For the nonconformists by nature, this burger has it all. Double burger, cheddar cheese and bacon. What more can you ask for?",
                "visible" => true,
                "price" => 3.8,
                "img" => "https://opinioni.it/Uploads/Products/22852/Screenshot_2017-03-11-22-57-45-1_large.png",
            ],
            [
                "restaurant_id" => "13",
                "name" => "MIXED SALAD",
                "ingredients" => "corn, tomato, salad,",
                "description" => "Only 40 calories. This salad is a delight for everyone. Don't give up on taste and enjoy a blend of ingredients that explode in your mouth like fireworks.",
                "visible" => true,
                "price" => 2.1,
                "img" => "https://burgerking.com.mt/wp-content/uploads/2020/03/5.Green-Salad.png",
            ],
            [
                "restaurant_id" => "13",
                "name" => "KING FUSION PERUGINA",
                "ingredients" => "ice cream, chocolate, vanilla",
                "description" => "KING FUSION® Perugina®. Dolci praline al cioccolato nel nostro delizioso gelato con aroma di vaniglia.",
                "visible" => true,
                "price" => 4.3,
                "img" => "https://www.bidibee.com/file/5f76037f10000025eeb0c8b5/MARKETS/5f76044f1000002beeb0c8b6/ITEMS/60376743110000c876b699b6/small_BnaFah2XuxvGVcP.jpg",
            ],
            [
                "restaurant_id" => "13",
                "name" => "ONION RINGS",
                "ingredients" => "onion, olive oil",
                "description" => "Here we come full circle for all onion ring fans. Dip them in a sauce and enjoy. Or munch on the golden breading first and then the onion. Exactly how you want!",
                "visible" => true,
                "price" => 4,
                "img" => "https://www.seekpng.com/png/detail/52-522297_onion-rings-burger-king-onion-rings.png",
            ],
            [
                "restaurant_id" => "13",
                "name" => "PLANT BASED WHOPPER",
                "ingredients" => "burger grilled, tomato, lettuce, gherkins, ketchup and mayonnaise",
                "description" => "Juicy 100% vegetable burger grilled on our flame, fresh tomato, onion cut at the moment, lettuce, gherkins, ketchup and mayonnaise. Taste? 100% Whopper. Try it, but you won't believe it.",
                "visible" => true,
                "price" => 5,
                "img" => "https://funnyvegan.com/wp-content/uploads/2021/03/Funny-Vegan-news-plant-based-Whooper.png",
            ],
            [
                "restaurant_id" => "13",
                "name" => "french frise",
                "ingredients" => "potatos, olive oil",
                "description" => "Our KING Chips are worthy of a king: delicious potatoes, golden color and crunchiness are the characteristics that make them unique.",
                "visible" => true,
                "price" => 3.5,
                "img" => "https://fastfoodnutrition.org/item-photos/full/1470_s.jpg",
            ],
            // the garage plates
            [
                "restaurant_id" => "8",
                "name" => "Margherita Pizza",
                "ingredients" => "Manitoba flour 200 g 00 flour 300 g, Water 300 ml, Extra virgin olive oil 35 g, Salt up to 10 g, Fresh brewer's yeast 5 g, Tomato pulp 500 g, Fiordilatte 400 g, Dried oregano 1 tbsp, Salt up to 1 tsp, Basil to taste, Extra virgin olive oil to taste",
                "description" => "The Margherita pizza is the typical Neapolitan pizza, topped with tomato, mozzarella (traditionally the fior di latte is used, not that of buffalo), fresh basil, salt and oil; it is, together with pizza marinara, the most popular Italian pizza. ...",
                "visible" => true,
                "price" => 4.5,
                "img" => "https://lh3.googleusercontent.com/proxy/Cxp-jAC5ZOItRhTe1w0dcibFqRoC5EqCEE9YC7XqqSPgdIPQFT-488SkYX40L0SxXMT6nSExGE5dkmGAZ9rcZp7aI1HmtNb8qG30xV__GfhG9eDcwLKYgmC8",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Marinara Pizza",
                "ingredients" => "Manitoba flour 200 g 00 flour 300 g, Water 300 ml, Extra virgin olive oil 35 g, Salt up to 10 g, Fresh brewer's yeast 5 g, Tomato pulp 500 g, Dried oregano 1 tbsp, Salt up to 1 tsp, Basil to taste, Extra virgin olive oil to taste",
                "description" => "also known as pizza alla marinara, is a style of Neapolitan pizza in Italian cuisine seasoned with only tomato sauce, extra virgin olive oil, oregano and garlic. The name has little to do with the marinara sauce, besides sharing a similar origin. It is supposedly the most ancient tomato-topped pizza",
                "visible" => true,
                "price" => 3.8,
                "img" => "https://www.donnamoderna.com/content/uploads/2012/03/Pizza-alla-marinara-725x545.jpg",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Diavola Pizza",
                "ingredients" => "400 gr of flour Tomato sauce to taste Oregano (optional), 200 ml of water, ½ stick of yeast, Salt, extra virgin olive oil to taste, Spicy Negronetto to taste, 200 gr of mozzarella, Tomato sauce to taste, Oregano (optional)",
                "description" => "In Italian, pizza diavola means “deviled” pizza. And in this case, deviled means one thing: spicy.",
                "visible" => true,
                "price" => 5,
                "img" => "https://www.pizzeriabraceriafuego.it/images/2020/08/28/71_main.png",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Tuna and Onion Pizza",
                "ingredients" => "1 (2.6 oz.) Pouch - Yellowfin Tuna in Extra Virgin Olive Oil. 1, 12″ whole wheat pizza crust, unbaked. ⁄4 cup pizza sauce. 10 Pearl onions, peeled. 1 Tbsp. fresh oregano, chopped (or 1 tsp. dried oregano) ⅓ cup mozzarella cheese. ⁄4 cup Parmesan cheese.",
                "description" => "The Tuna and Onion Pizza is a pizza rich in seasoning with a strong flavor, a crunchy pizza dough base stuffed with tomato sauce, onions, tuna and stringy mozzarella. The Pizza with tuna and onions is ideal when you want to enjoy a very tasty single dish excellent to bring to the table with a nice iced beer for a dinner with friends.",
                "visible" => true,
                "price" => 5.5,
                "img" => "https://media.gettyimages.com/photos/pizza-tuna-onion-herbs-on-plate-picture-id182878095?s=170667a",
            ],
            [
                "restaurant_id" => "8",
                "name" => "4 seasons pizza",
                "ingredients" => "Artichokes, tomatoes, basil, prosciutto, ham, mushrooms, olives",
                "description" => "Pizza quattro stagioni (four seasons pizza) is a variety of pizza in Italian cuisine that is prepared in four sections with diverse ingredients, with each section representing one season of the year. It is a very popular pizza in Italy, and has been described as a 'classic', 'famous' and 'renowned' Italian pizza",
                "visible" => true,
                "price" => 5.5,
                "img" => "https://image.freepik.com/free-photo/italian-pizza-four-seasons-isolated-white_136401-2328.jpg",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Roman Braised Beef sandwich(Picchiapò)",
                "ingredients" => "beef, brad, tomato, onion",
                "description" => "this simple, rustic dish of shredded beef braised in tomatoes and onions make a great stew and a fantastic sandwich filling.",
                "visible" => true,
                "price" => 6.7,
                "img" => "https://www.ilariabarisi.it/wp-content/uploads/2019/03/carne-picchiapo-per-web.jpg",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Italian Pecorino, Parsley Sandwich",
                "ingredients" => "Pecorino, Parsley, brad, anchovy",
                "description" => "This crusty sandwich only calls for a handful of ingredients—pecorino, parsley, and anchovy—but has big flavors.",
                "visible" => true,
                "price" => 7.2,
                "img" => "https://image.freepik.com/free-photo/italian-pizza-four-seasons-isolated-white_136401-2328.jpg",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Softshell Crab Sandwich with Slaw",
                "ingredients" => "Crab, Parsley, Slaw",
                "description" => "A crisp collard slaw and tangy tartar and cocktail sauces top pan-fried softshell crabs in this classic sandwich.",
                "visible" => true,
                "price" => 7.6,
                "img" => "https://www.saveur.com/uploads/2019/01/03/XSPPKHJVFUKJQDJNOPDH7CZZJ4.jpg?width=785",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Turkish Grilled Cheese (Kumru)",
                "ingredients" => "Cheese, brad, Kumru",
                "description" => "This specialty of Çesme, a small beach town in Turkey, is one of the world’s great grilled cheese sandwiches, in which the cheese itself is grilled before getting slipped into toasted bread with raw tomato and optional (but highly recommended) toppings of griddled sausage and pickled cucumbers and chiles",
                "visible" => true,
                "price" => 7.2,
                "img" => "https://lh3.googleusercontent.com/proxy/os5Gv68ERBJ2vXYzMiHsB3W-ifCb-melgpWNibGA-TKi_HR4koerxNgGKVbqsq2zYZcNB4t3UMzANdVxW6L8MTuhyXVkwRFNHBidSQB1ocC_kA",
            ],
            [
                "restaurant_id" => "8",
                "name" => "Pork Belly Gyro",
                "ingredients" => "Pork meet, brad, tomato, cucumbers",
                "description" => "By starting with a low cooking temperature and then switching to a high one, this pork belly with perfect texture",
                "visible" => true,
                "price" => 6.7,
                "img" => "https://www.kitchensanctuary.com/wp-content/uploads/2017/11/Pork-Gyros-with-Homemade-Tzatziki-square-FS-500x500.jpg",
            ],
            // mexican
            [
                "restaurant_id" => "2",
                "name" => "beef burritos",
                "ingredients" => "Beef Burrito Filling – juicy and packed with flavour! Plain white rice – or try brown rice, quinoa, or this Mexican Red Rice!)Corn. Black beans. Cabbage or lettuce. Diced tomato. Red onion. Cheese",
                "description" => "The word burrito means 'little donkey' in Spanish, being the diminutive form of burro, or 'donkey'. The name burrito, as applied to the dish, possibly derives from the tendency for burritos to contain a lot of different things similar to how a donkey would be able to carry a lot.",
                "visible" => true,
                "price" => 18,
                "img" => "https://images-gmi-pmc.edge-generalmills.com/3f2a43ee-fbec-46bc-b26a-0e6f64d85a41.jpg",
            ],
            [
                "restaurant_id" => "2",
                "name" => "tortillas",
                "ingredients" => "Massa, Nixtamal",
                "description" => "Tortillas made from nixtamalized maize meal—masa de maíz— are the oldest variety of tortilla. They originated in Mexico, and remain popular throughout the Americas. Peoples of the Oaxaca region in Mexico first made tortillas at the end of the Villa Stage (1500 to 500 BC)",
                "visible" => true,
                "price" => 7.5,
                "img" => "https://lh3.googleusercontent.com/proxy/X3HdVmIAm3vV3NxbshJsW27Efy_kArzXTrvQVAvJAOKP2jE3h3-FnlERJVXcyaFymdyzAIgnr-Cr-nDPL-ZoJSjXBKIIO4A-NHAi5A_x5dv2FfDr2dFAbFl-PL7TjbE",
            ],
            [
                "restaurant_id" => "2",
                "name" => "tacos",
                "ingredients" => "Olive oil – helps brown the beef better. Lean ground beef – I like to use 85% lean angus. ... Garlic – use fresh chopped. ...Spices – chili powder, cumin, onion powder, salt and pepper. Tomato sauce – this makes the taco filling rich and saucy.",
                "description" => "The origins of the taco are not precisely known, and etymologies for the culinary usage of the word are generally theoretical.Taco in the sense of a typical Mexican dish comprising a maize tortilla folded around food is just one of the meanings connoted by the word, according to the Real Academia Española, publisher of Diccionario de la Lengua Española",
                "visible" => true,
                "price" => 6,
                "img" => "https://www.giallozafferano.it/images/175-17533/Tacos-veloci_650x433_wm.jpg",
            ],
            [
                "restaurant_id" => "2",
                "name" => "Guacamole",
                "ingredients" => "avocados - peeled, pitted, and mashed, lime, juiced teaspoon salt, cup diced onion, tablespoons chopped fresh cilantro, roma (plum) tomatoes, diced, teaspoon minced garlic, pinch ground cayenne pepper",
                "description" => "Guacamole (called Guacamol in Central America and Cuba) is a Mexican dip made of avocados, salt and sometimes tomatoes. Various herbs can be added too, such as chives. It is depicted as a green, creamy dip or garnish. It is often served as a dip or garnish with Mexican foods such as tacos and tortilla chips.",
                "visible" => true,
                "price" => 16,
                "img" => "https://freepikpsd.com/media/2019/10/guacamole-png-Transparent-Images.png",
            ],
            [
                "restaurant_id" => "2",
                "name" => "Pozole",
                "ingredients" => "ounces dried guajillo, ancho, or a combination of both, chili pods, Salt, large (108 ounce, 6 lb 12 oz, 3 kg) can white hominy, drained and rinsed, pounds pork shoulder (preferably with bone), cut into 1 to 1 1/2 inch cubes (can also use pork shanks), make sure to use a cut well marbled with fat, cloves garlic, cloves roughly chopped, and whole cloves, bay leaves, teaspoon ground cumin, tablespoons of dry oregano (Mexican oregano if available)",
                "description" => "Pozole can be prepared in many ways, but all variations include a base of cooked hominy in broth. Typically pork, or sometimes chicken, is included in the base. Vegetarian recipes substitute beans for the meat.",
                "visible" => true,
                "price" => 13,
                "img" => "https://www.muydelish.com/wp-content/uploads/2020/12/How-To-Make-Pozole-500x500.jpg",
            ],
            [
                "restaurant_id" => "2",
                "name" => "Chiles en nogada",
                "ingredients" => "pounds ground turkey thigh meat, Kosher salt, Tbsp olive oil or canola oil, medium onion, finely chopped, cloves garlic, peeled and finely chopped, Tbsp butter, teaspoon ground cinnamon, teaspoon freshly ground black pepper,teaspoon ground cloves, crushed, fire roasted tomatoes, cup of golden raisins, Tbsp blanched and slivered almonds, roughly chopped, apple, peeled, cored, chopped",
                "description" => "We make our chiles en nogada based on an old family recipe from Yuriria, Guanajuato that dates back at least until the 1950s. Chiles en nogada are meat stuffed poblano chiles bathed in nogada, a walnut cream sauce and garnished with pomegranate seeds and parsley.",
                "visible" => true,
                "price" => 11,
                "img" => "https://www.vitamix.com/media/other/images/Chiles-en-Nogado-470x449.jpg",
            ],
            [
                "restaurant_id" => "2",
                "name" => "Corn on the cob",
                "ingredients" => "corn",
                "description" => "Corn on the cob is a culinary term used for a cooked ear of freshly picked maize from a cultivar of sweet corn. Sweet corn is the most common variety of maize eaten directly off the cob",
                "visible" => true,
                "price" => 5,
                "img" => "http://farm6.static.flickr.com/5134/5466418950_2df6f56bb7.jpg",
            ],
            [
                "restaurant_id" => "2",
                "name" => "Enchilada",
                "ingredients" => "Chicken, onion, Onion and diced green chiles, tortillas, Cheese, Toppings",
                "description" => "The Royal Spanish Academy defines the word enchilada, as used in Mexico, as a rolled maize tortilla stuffed with meat and covered with a tomato and chili sauce.",
                "visible" => true,
                "price" => 12,
                "img" => "https://www.pngkey.com/png/full/193-1931777_1-two-green-sauce-enchiladas-enchilada.png",
            ],
            [
                "restaurant_id" => "2",
                "name" => "Yellow mole",
                "ingredients" => "10 dried guajillo chiles, washed. annatto seeds (achiote),  ground canela (Mexican cinnamon), whole cloves., tsp. cumin seed., tsp. dry Mexican oregano, toasted., Mexican saffron, corn oil.",
                "description" => "a traditional sauce and marinade originally used in Mexican cuisine",
                "visible" => true,
                "price" => 4,
                "img" => "https://cdn.kiwilimon.com/recetaimagen/32150/th5-640x426-37045.jpg",
            ],
            [
                "restaurant_id" => "2",
                "name" => "Tostadas",
                "ingredients" => " refried beans, shredded cheese, salsa",
                "description" => "What should you do with stale tortillas? Why, fry them of course! Literally meaning toasted, tostadas are a simple but delicious dish involving corn tortillas fried in boiling oil until they become crunchy and golden. These are then served alone or piled high with any number of garnishes. Popular toppings include frijoles (refried beans), cheese, cooked meat, seafood and ceviche.",
                "visible" => true,
                "price" => 6.7,
                "img" => "https://tastesbetterfromscratch.com/wp-content/uploads/2020/01/Tostadas-5-500x500.jpg",
            ],
            // sushi 
            [
                "restaurant_id" => "3",
                "name" => "WAKAME",
                "ingredients" => "marinated wakame (seaweed) salad",
                "description" => "Add one of our many appetizers or salads to your meal.",
                "visible" => true,
                "price" => 3.7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/07/ENTREES_SALADES_SALADE-WAKAME_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "EDAMAME BEANS",
                "ingredients" => "beans",
                "description" => "Add one of our many appetizers or salads to your meal.",
                "visible" => true,
                "price" => 3.5,
                "img" => "https://sushishop.com/wp-content/uploads/2019/07/ENTREES_SALADES_FEVEZ-EDAMAME_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "SPRING ROLL",
                "ingredients" => "Thin rice noodles. Butter lettuce. Red cabbage (or green cabbage) Carrot. Cucumber. Jalapeño (skip if you're very sensitive to spice) Green onion, cilantro and mint.",
                "description" => "Served with sweet chili sauce.",
                "visible" => true,
                "price" => 6,
                "img" => "https://sushishop.com/wp-content/uploads/2019/09/SS_SITE-WEB_ENTREES_SALADES_ROULEAU-IMPERIAL_1024x1024_JUIL19-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "AVOCADO",
                "ingredients" => "avocado, sesame, rice",
                "description" => "6 pieces. Small rolls containing two or three ingredients. These come in sixes and are a great accompaniment or perfect for a quick bite. Simple and delicious.",
                "visible" => true,
                "price" => 6.4,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/HOSOMAKI_AVOCADO_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "MAGURO",
                "ingredients" => "tuna, rice",
                "description" => "2 pieces. A fresh fish or seafood slice gently placed on vinegar rice that comes in twos. The perfect combination of fresh flavours and textures.",
                "visible" => true,
                "price" => 5.7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/07/NIGIRI_SASHIMI_MAGURO_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "TWIN SALMON",
                "ingredients" => "salmon, smoked salmon, avocado, green onion, red masago, light mayo, sesame",
                "description" => "8 pieces. Medium sized rolls served in eight bite-sized pieces. All sorts of flavour combinations for the beginner to the sushi expert.",
                "visible" => true,
                "price" => 8,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/MAKI_DEUX-SAUMONS_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "RED VELVET",
                "ingredients" => "tuna, avocado, red masago, spicy, sesame and poke sauce, nori, sesame, crispy rice",
                "description" => "5 pieces. Each of our Blossom rolls offers ingredients in the roll as well as on top mimicking the beautiful Japanese flower.",
                "visible" => true,
                "price" => 8.3,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/BLOSSOM_REDVELVET-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "TONKOTSU",
                "ingredients" => "Choice of protein: Grilled chicken Seafood (salmon, shrimp, kanikama) Shrimp tempura Option: Spicy Extras: Double your protein! Egg (1/2) Chicken Seafood Shrimp Tempura",
                "description" => "Japanese-inspired Ramen soups by Sushi Shop with 2 unique broths options. You can even double your protein for an even more filling meal. A true Japanese specialty with flavours of pork, miso and a hint of garlic. This rich and smooth soup is a must-try!",
                "visible" => true,
                "price" => 7.7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/Grandesoupe-ramen-255x210.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "DIABLO T",
                "ingredients" => "Blossom: 5 Diablo Hosomaki: 6 Chef’s choice 1 Wakame Salad (1.5 oz)",
                "description" => "11 pieces. Our combos are prepared throughout the day from fresh ingredients.",
                "visible" => true,
                "price" => 12,
                "img" => "https://sushishop.com/wp-content/uploads/2019/07/COMBOS_DIABLO_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Combo M",
                "ingredients" => "Sumomaki: 5 Salmon Kamikaze Maki: 4 Ebi Maki Hosomaki: 3 Avocado Nigiri: 1 Syake, 1 Ebi",
                "description" => "Our combos are prepared throughout the day from fresh ingredients.",
                "visible" => true,
                "price" => 15,
                "img" => "https://sushishop.com/wp-content/uploads/2019/07/COMBOS_M-RIZBRUN_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "SHRIMP",                
                "ingredients" => "shrimp, kanikama, lettuce, carrot, green onion, rice, sesame, rice paper",
                "description" => "2 pieces. Served with our sesame sauce.",
                "visible" => true,
                "price" => 7.5,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/MAKI-PRINTEMPS_CREVETTES_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Sushi Tacos LOBSTER",
                "ingredients" => "lobster, avocado, lettuce, coriander, roasted garlic, green onion, spicy light mayo, sesame sauce, jalapeño slice, sesame, crispy wonton shell",
                "description" => "2 pieces and So much fun to eat!",
                "visible" => true,
                "price" => 8.7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/TACOS_HOMARD2_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Tartare TUNA",
                "ingredients" => "tuna, tempura, wasabi, soy sauce, green onion, sesame",
                "description" => "A generous portion of protein and fresh ingredients, served with crispy wonton chips. Our tartars are a great low caloric option that will satisfy your cravings.",
                "visible" => true,
                "price" => 8.3,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/TARTARES_THON_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Platters VEGETARIAN",
                "ingredients" => "Inari (4) Kappa (3) Avocado (3) Oshinko (3) Akanasu (3) Vegetarian (10)",
                "description" => "26 pieces, Beware, our sushi platters could steal the show at your next event!",
                "visible" => true,
                "price" => 6.7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/PLATEAUX_VEGE_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "POKE BOMB",
                "ingredients" => "tuna and salmon poke bites, crispy wonton, teriyaki bomb, shrimp tartare maki, wakame, edamame beans, imperial roll, sweet chili sauce",
                "description" => "Our Bento boxes are a complete meal ready-to-go!",
                "visible" => true,
                "price" => 7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/08/SS_SITE-WEB_BOITEBENTO_POKEBOMB_1024x1024_JUIL19-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "SPICY TUNA & MANGO",
                "ingredients" => "tuna, mango, jalapeño, crispy wonton, lettuce, carrot, green onion, spicy sauce, Japanese mayo, spicy light mayo, crispy sticky rice, nori",
                "description" => "Our Sushi Burrito are a good option for a meal on-the-go! Served with spicy light mayo, soy, sesame or Ying Yang sauce.",
                "visible" => true,
                "price" => 7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/BURRITOS_THONEPICEMANGUE_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Karaage Chicken BOWL",
                "ingredients" => "10 pieces, Karaage chicken, avocado, carrot, cucumber, rice with a choice of soy or ponzu sauce, roasted garlic, Japanese spices, sesame, lemon wedge",
                "description" => "Tender brown meat in a crispy Japanese batter. Served with spicy light mayo, Japanese mayo, sweet chili, Yin Yang or teriyaki sauce.",
                "visible" => true,
                "price" => 9.2,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/pouletkaraage-repas-350x321.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Temari CRISPY LOBSTER",
                "ingredients" => "4 pieces, Each Temari is prepared with distinctive ingredients, inside and out, giving them a unique character and personality.",
                "description" => "Ext. crispy lobster, black masago, Japanese mayo Int. lobster, crab, shrimp, mango, green onion, spicy light mayo",
                "visible" => true,
                "price" => 7,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/TEMARI_CRISPYLOBSTER_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Temari TUNA TATAKI",
                "ingredients" => "Ext. tuna tataki, Japanese mayo, green onion, Japanese spices Int. avocado, tempura, sesame sauce",
                "description" => "Each Temari is prepared with distinctive ingredients, inside and out, giving them a unique character and personality.",
                "visible" => true,
                "price" => 10.3,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/TEMARI_THONTATAKI_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Temari VEGGIE BOMB",
                "ingredients" => "Ext. Japanese mayo, teriyaki sauce, sesame, green onion Int. torch- seared red pepper, carrot, oshinko, mozzarella, spicy light mayo",
                "description" => "4 pieces, Each Temari is prepared with distinctive ingredients, inside and out, giving them a unique character and personality. Served with spicy light mayo, soy, sesame or Yin Yang sauce.",
                "visible" => true,
                "price" => 9.2,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/TEMARI_VEGGIEBOMB_-350x350.png",
            ], 
            [
                "restaurant_id" => "3",
                "name" => "Maki BLACK MAMBATM",
                "ingredients" => "shrimp tempura, salmon, kanikama, red and black masago, spicy light mayo, Japanese mayo, green onion",
                "description" => "8 pieces. Medium sized rolls served in eight bite-sized pieces. All sorts of flavour combinations for the beginner to the sushi expert.",
                "visible" => true,
                "price" => 7.8,
                "img" => "https://sushishop.com/wp-content/uploads/2019/06/MAKI_BLACK-MAMBA_-350x350.png",
            ], 
            // fajke plates of restaurant 1
            [
                "restaurant_id" => "1",
                "name" => "someone else",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "https://w7.pngwing.com/pngs/768/586/png-transparent-cooked-meat-with-tomatoes-and-flat-bread-gyro-buffalo-wing-chicken-sandwich-cheeseburger-french-fries-tzatziki-food-recipe-chicken-meat.png",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 2",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 3",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 4",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 5",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 6",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 7",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 8",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 9",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 10",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 11",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 12",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 13",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 14",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 15",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],
            [
                "restaurant_id" => "1",
                "name" => "someone else 16",
                "ingredients" => "someone else",
                "description" => "someone else",
                "visible" => true,
                "price" => 56.5,
                "img" => "",
            ],       
        ];

        foreach($plates as $plate){
            // instance
            $new_plate = new Plate();
            // populate
            $new_plate->restaurant_id = $plate['restaurant_id'];
            $new_plate->name = $plate['name'];
            $new_plate->slug = Str::slug( $new_plate->name, '-');
            $new_plate->ingredients = $plate['ingredients'];
            $new_plate->description = $plate['description'];
            $new_plate->visible = $plate['visible'];
            $new_plate->price = $plate['price'];
            $new_plate->img = $plate['img'];
            // save
            $new_plate->save();
        } 
    }
}
