services:
  - type: web
    name: deliveboo-laravel
    runtime: docker
    repo: https://github.com/182Marco/deliveBoo
    branch: master
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
